### ISSUE TITLE
AC FGC Iteration #1 To-Do

### ISSUE THREAD

**Issue by apmcguigan** [apmcguigan/AC_FGC.github.io#1]
### Code Changes
- [ ] Update favicon image
- [ ] Update or remove google analytics tags
- [ ] Delete SFV Dojo link
- [ ] Combine Social Media Section with Tournament Organizers and Streamers sections

### Web Domain

- [ ] Price for AtlanticCanadaFGC domains?
- [ ] Alternatively create new github called AtlanticCanadaFGC so the URL is AtlanticCanadaFGC.github.io

### AC Cup Separate Page
- [ ] Embed google sheets for up to date standings
- [ ] Embed google calendar to track events on the circuit
